import Head from 'next/head'

import styles from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Invite - Confirmação de presença</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <div className={styles.sectionContent}>
          <h6>A melhor plataforma de confirmação de presença.</h6>
          <h1>Seu evento, <br /> do seu jeito.</h1>
          <span>Conheça o minisite que vai elevar o nível do seu evento.</span>
          <a href='/create'>Crie o seu evento grátis.</a>
        </div>
      </main>
      <section className={styles.sectionItem}>
          <div className={styles.content}>
            <span>Configure em poucos passos</span>
            <h2>São poucos cliques para uma página elegante.</h2>
            <p>Tudo no invite é fácil de criar para que você possa focar no que realmente importa.</p>
          </div>
          <img src='/images/image-1.svg' alt='Image 1' />
        </section>

        <section className={styles.sectionItem}>
          <img src='/images/image-2.svg' alt='Image 2' />
          <div className={styles.content}>
            <span>Impossível não se apaixonar</span>
            <h2>Design sedutor e conteúdo encatador.</h2>
            <p>O seu invite já nasce com um visual profissional que engrandece seu convite.</p>
          </div>
        </section>

        <div className={styles.planner}>
          
        </div>
    </>
  )
}
